import { ToastProvider } from '@contact-tracker/ui-shared';
import './global.css';

export const metadata = {
  title: 'Welcome to tracker-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
