import { ToastProvider } from '@contact-tracker/ui-components';
import { DatabaseProvider } from '../lib/context/db-provider';
import './global.css';

export const metadata = {
  title: 'Welcome to Contact Tracker',
  description: 'Generated by create-nx-workspace',
};

export const viewport = {
  // Use daisyUI primary colors for the browser/status bar
  // Light: #570df8 | Dark: #6610f2 (default primary variants)
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#570df8' },
    { media: '(prefers-color-scheme: dark)', color: '#1d232a' },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <DatabaseProvider>
          <ToastProvider>{children}</ToastProvider>
        </DatabaseProvider>
      </body>
    </html>
  );
}
