FROM mcr.microsoft.com/dotnet/sdk:8.0

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo git \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR /workspace
RUN chown -R $USERNAME:$USERNAME /workspace

USER $USERNAME

RUN dotnet tool install --global dotnet-ef --version 8.*
ENV PATH="$PATH:/home/$USERNAME/.dotnet/tools"
ENV DOTNET_CLI_HOME=/home/$USERNAME

EXPOSE 5238

CMD ["sleep", "infinity"]