FROM mcr.microsoft.com/dotnet/sdk:8.0

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME --shell /usr/bin/zsh \
    && apt-get update \
    && apt-get install -y sudo git zsh \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR /workspace
RUN chown -R $USERNAME:$USERNAME /workspace

ENV DOTNET_ROOT=/usr/share/dotnet
ENV PATH=/usr/share/dotnet:/usr/bin:$PATH

RUN mkdir -p /vscode && chown -R $USERNAME:$USERNAME /vscode

USER $USERNAME

RUN dotnet tool install --global dotnet-ef --version 8.*
ENV PATH="$PATH:/home/$USERNAME/.dotnet/tools"
ENV DOTNET_CLI_HOME=/home/$USERNAME
ENV SHELL=/usr/bin/zsh
ENV HOME=/home/vscode

EXPOSE 5238